debug: false
data-save: PT6M
language: "en_us"
dump-default: true
biome-search-resolution: 4
cache:
  carver: 512
  structure: 32
  sampler: 128
master-disable:
  caves: false
script:
  max-recursion: 1000